project:
  type: website
  output-dir: _site

website:
  title: "Saran Kumar Vajja"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Blog

    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source
